//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ap_Lua_LuaControlEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ap.Lua.ControlEvent), typeof(System.Object));
		L.RegFunction("New", _CreateAp_Lua_LuaControlEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Fun", get_Fun, set_Fun);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAp_Lua_LuaControlEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Ap.Lua.ControlEvent obj = new Ap.Lua.ControlEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Ap.Lua.LuaControlEvent.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fun(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Lua.ControlEvent obj = (Ap.Lua.ControlEvent)o;
			LuaInterface.LuaFunction ret = obj.Fun;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Fun on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Fun(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Lua.ControlEvent obj = (Ap.Lua.ControlEvent)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.Fun = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Fun on a nil value" : e.Message);
		}
	}
}

