//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ap_Managers_FormManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ap.Managers.FormManager), typeof(Ap.Managers.ManagerBase<Ap.Managers.FormManager>));
		L.RegFunction("Awake", Awake);
		L.RegFunction("Show", Show);
		L.RegFunction("Close", Close);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Awake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ap.Managers.FormManager obj = (Ap.Managers.FormManager)ToLua.CheckObject(L, 1, typeof(Ap.Managers.FormManager));
			obj.Awake();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ap.Managers.FormManager obj = (Ap.Managers.FormManager)ToLua.CheckObject(L, 1, typeof(Ap.Managers.FormManager));
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.Show(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ap.Managers.FormManager obj = (Ap.Managers.FormManager)ToLua.CheckObject(L, 1, typeof(Ap.Managers.FormManager));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int o = obj.Close(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

