//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ap_Managers_ManagerManagersWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ap.Managers.ManagerManagers), typeof(Ap.Base.SingletonBase<Ap.Managers.ManagerManagers>));
		L.RegFunction("Clear", Clear);
		L.RegFunction("New", _CreateAp_Managers_ManagerManagers);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("A", get_A, null);
		L.RegVar("E", get_E, null);
		L.RegVar("F", get_F, null);
		L.RegVar("G", get_G, null);
		L.RegVar("L", get_L, null);
		L.RegVar("N", get_N, null);
		L.RegVar("O", get_O, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAp_Managers_ManagerManagers(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Ap.Managers.ManagerManagers obj = new Ap.Managers.ManagerManagers();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Ap.Managers.ManagerManagers.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)ToLua.CheckObject(L, 1, typeof(Ap.Managers.ManagerManagers));
			obj.Clear();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_A(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.AssetBundleManager ret = obj.A;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index A on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_E(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.EventManager ret = obj.E;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index E on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_F(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.FormManager ret = obj.F;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index F on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_G(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.GameManager ret = obj.G;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index G on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_L(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.LuaManager ret = obj.L;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index L on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_N(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.NetworkManager ret = obj.N;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index N on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_O(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ap.Managers.ManagerManagers obj = (Ap.Managers.ManagerManagers)o;
			Ap.Managers.ObjectPoolManager ret = obj.O;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index O on a nil value" : e.Message);
		}
	}
}

