//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ap_UI_FormCtrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ap.UI.FormCtr), typeof(Ap.Base.MonoBehaviourEx));
		L.RegFunction("BindView", BindView);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BindView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ap.UI.FormCtr obj = (Ap.UI.FormCtr)ToLua.CheckObject<Ap.UI.FormCtr>(L, 1);
			Ap.Base.IView arg0 = (Ap.Base.IView)ToLua.CheckObject<Ap.Base.IView>(L, 2);
			obj.BindView(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

