// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Protocol.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Msg
{

    [global::ProtoBuf.ProtoContract(Name = @"LOGIN_INFO")]
    public partial class LoginInfo
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"USER_NAME")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"USER_PWD")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserPwd { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"TOKEN")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"COMMON_INFO")]
    public partial class CommonInfo
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"MSG")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"NUMS", IsPacked = true)]
        public int[] Nums { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"PLAYER")]
    public partial class Player
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ID")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"NAME")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021
